CREATE TABLE IF NOT EXISTS UTILIZATORI (NUME VARCHAR ,PAROLA VARCHAR NOT NULL ,ACTIVITATE INTEGER DEFAULT 0 , DESCRIPTOR INTEGER DEFAULT 0);

CREATE TABLE IF NOT EXISTS MESAJE (CONV_ID INTEGER NOT NULL, UTILIZATOR1 VARCHAR NOT NULL, UTILIZATOR2 VARCHAR NOT NULL, MESAJ VARCHAR NOT NULL, MESAJ_ID INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS "MESAJE NECITITE"(ONLINE VARCHAR NOT NULL, OFFLINE VARCHAR NOT NULL, MESAJ VARCHAR NOT NULL, CONV_ID INTEGER NOT NULL);

SELECT * FROM UTILIZATORI;
SELECT * FROM MESAJE ORDER BY CONV_ID;
SELECT * FROM "MESAJE NECITITE" ORDER BY CONV_ID;
